### ISSUE TITLE
consider adding GH Action to auto-add PRs and issues to our PACTA board

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.prepare.pacta.indices#32]
based on https://github.com/RMI-PACTA/pacta.portfolio.allocate/blob/main/.github/workflows/add-prs-and-issues-to-project.yml

**Comment by jdhoffa** [comment]
@cjyetman I have added an action here to track issues and PRs in the "repos @jdhoffa maintains" board. 

Would you like to track issues here for yourself too? or can I close this issue.

**Comment by cjyetman** [comment]
nope, all good
