### ISSUE TITLE
consider whether `ishares_indices_*.rds` files should be included in output

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.prepare.pacta.indices#46]
The portfolios we download from iShares have never been included in the "PACTA_analysis inputs" folders before, and they are not used as inputs to PACTA_analysis process directly, so I'm not totally convinced that they should be included in the outputs of data.prep. What has been included in the outputs previously was the output of PACTA_analysis using those as the input portfolios. Maybe it's convenient to have the portfolios there too 🤷🏻? Not really sure. But clearly there is no purpose for having them included in the pacta-data repo, and conceptually (to me anyway) this repo is intended to build the folder for a given quarter that should be a drop-in to the pacta-data repo.

Thanks @cjyetman

**Comment by jdhoffa** [comment]
Migrated to https://github.com/RMI-PACTA/workflow.prepare.pacta.indices as per @cjyetman suggestion

**Comment by cjyetman** [comment]
> * `workflow.pata.report` calls the `workflow.pacta` image: both to run the "input portfolio" and to run the "indices portfolios" (noting that "running the indices portfolios" is only something that's necessary to do when making a report)

I'm not 100% sure making `workflow.pata.report` run the input portfolio and multiple index portfolios all the way "through PACTA" on-the-fly, e.g. every time a portfolio is input, is an ideal solution. At least not in the context of the Webapp where time efficiency is desired. @AlexAxthelm?

**Comment by jdhoffa** [comment]
Could be fine if we cache the results?

**Comment by cjyetman** [comment]
Including the results of PACTA-processed indices in a "TM/Webapp analysis inputs" data directory has been our form of caching in the past. The new Webapp may have some capability of "cache the indices results somewhere the first time a portfolio is input", but TM will almost certainly not ever have that capability.

**Comment by jdhoffa** [comment]
Yup!

To clarify, all of my points above are towards a new workflow.* paradigm for the WebApp (and after)

Absolutely none of this should be considered before:
* PACTA COP CH 2024 is delivered successfully
* WebApp is proven to function with existing functionality

If we "move then improve" this discussion lands in the "improve" bucket.

**Comment by cjyetman** [comment]
> (not something we do or have ever tried to do, but could be possible as a feature in `workflow.pacta.report`?)

🤷🏻 maybe, but we have to keep in mind that in its current form `workflow.pacta.report` is intended to run as an ephemeral Docker instance, so wherever this cache would be, it would need to be somewhere outside of the Docker image, which implies the server running it has some resource available for that. An obvious candidate for that would be the data input storage, but I suspect/hope that would be a read-only resource.

**Comment by jdhoffa** [comment]
I will create a GH label that identifies that.
You may create similar tags to the TM important PROD repos you maintain, if you wish.

**Comment by jdhoffa** [comment]
I will close this in favor of https://github.com/RMI-PACTA/workflow.pacta.report/issues/3

I don't see any point in working on this, on this repository in it's current state, while it serves the TM use-case.
