### ISSUE TITLE
consider *not* re-installing PACTA packages over those installed in the transitionmonitor image

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.prepare.pacta.indices#53]
https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/dd1e27d74ba8b24a9eedf744ef9553436c47f257/Dockerfile#L26-L31

The Dockerfile uses a `transitionmonitordockerregistry.azurecr.io/rmi_pacta` base image, which should already have all the relevant PACTA R packages installed, because it should be a fully functional PACTA image. Currently, the Dockerfile re-installs all the PACTA R packages again (from GitHub, and therefore the most current versions), which can lead to differing versions of the PACTA R packages being used then those that are included in the base image, which can lead to errors if breaking changes occurred between those versions.

**Comment by AlexAxthelm** [comment]
Given that an important part of preparing indices is ensuring parity between the code running the analysis for a portfolio and the code running the analysis on the index benchmarks, I strongly support this.

**Comment by cjyetman** [comment]
superseded by #67
