### ISSUE TITLE
Allow for read-only inputs

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.prepare.pacta.indices#55]
Currently, the workflow writes tot he same directory that it reads data from. Since the input data (which is the outputs from `workflow.data.preparation`) should be read only, we need to update to write the output files from this process to a separate directory.

https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/7a7a0bb7b5f1a8162cee24d3a0eeea1d4ddb28f5/prepare_pacta_indices.R#L27-L30

cc @jdhoffa

**Comment by cjyetman** [comment]
closed by #77

**Comment by AlexAxthelm** [comment]
#77 didn't actually mark the inputs as read only.
