### ISSUE TITLE
consider using a parameterized `project_code` to target the same `ProjectParameters_` file in workflow.transition.monitor as the intended target

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.prepare.pacta.indices#79]
It would be advantageous if a user could specify a `project_code` so that it could target the same `ProjectParameters_[INITIATIVE].yml` [in workflow.transition.monitor](https://github.com/RMI-PACTA/workflow.transition.monitor/tree/main/parameter_files) as the one which the benchmarks are intended for.

e.g. when creating the config file here
https://github.com/RMI-PACTA/workflow.prepare.pacta.indices/blob/c3502eab84c635e60f5e6748f3b1870c799dd6e6/main.R#L151

This would remove the necessity of managing a separate config file in workflow.transition.monitor specifically for indices, e.g. [here](https://github.com/RMI-PACTA/workflow.transition.monitor/pull/245), and ensure that the same configuration of PACTA analysis is used for the specified quarter/initiative.

**Comment by jdhoffa** [comment]
I back this!
